package com.dictiographer.desktop.view;

import org.xhtmlrenderer.simple.FSScrollPane;
import org.xhtmlrenderer.simple.XHTMLPanel;
import org.xhtmlrenderer.swing.BasicPanel;
import org.xhtmlrenderer.swing.FSMouseListener;
import org.xhtmlrenderer.swing.LinkListener;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.util.List;

public class ContentsPanel extends JPanel {
    public JTextArea textArea1;
    public JPanel dictionariesPanel;
    public JPanel mainPanel;
    private FSScrollPane entryScrollPane;
    public XHTMLPanel entryPanel;
    public WrapLayout wrapLayout = new WrapLayout();

    public ContentsPanel() {
        setLayout(new BorderLayout());
        add($$$getRootComponent$$$(), BorderLayout.CENTER);


        wrapLayout.setHgap(1);
        wrapLayout.setVgap(1);
        wrapLayout.setAlignment(FlowLayout.LEFT);

        entryPanel.getSharedContext().getTextRenderer().setSmoothingThreshold(0);
        List l = entryPanel.getMouseTrackingListeners();
        for (Object o : l) {
            if (o instanceof LinkListener) {
                entryPanel.removeMouseTrackingListener((FSMouseListener) o);
            }
        }

        entryPanel.addMouseTrackingListener(new LinkListener() {
            @Override
            public void linkClicked(BasicPanel panel, String uri) {
                System.out.println(uri);
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setFocusable(false);
        panel1.add(panel2, BorderLayout.CENTER);
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(false);
        splitPane1.setDividerLocation(86);
        splitPane1.setDividerSize(5);
        splitPane1.setEnabled(true);
        splitPane1.setFocusable(false);
        splitPane1.setOneTouchExpandable(false);
        panel2.add(splitPane1, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        splitPane1.setLeftComponent(panel3);
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        entryScrollPane = new FSScrollPane();
        entryScrollPane.setHorizontalScrollBarPolicy(30);
        entryScrollPane.setVerticalScrollBarPolicy(20);
        panel3.add(entryScrollPane, BorderLayout.CENTER);
        entryPanel = new XHTMLPanel();
        entryScrollPane.setViewportView(entryPanel);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        splitPane1.setRightComponent(panel4);
        panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel4.add(scrollPane1, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
        dictionariesPanel = new JPanel();
        dictionariesPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 0, 0));
        panel1.add(dictionariesPanel, BorderLayout.NORTH);
        dictionariesPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
