package com.dictiographer.desktop.view;

import com.dictiographer.desktop.presenter.Presenter;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainPanel {
    public JPanel containerPanel;
    public JTabbedPane indexTabbedPane;
    public JSplitPane mainSplitPane;
    public JPanel cardsPanel;

    public MainPanel(Presenter p) {
        indexTabbedPane.addChangeListener(p);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        containerPanel = new JPanel();
        containerPanel.setLayout(new BorderLayout(0, 0));
        containerPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        mainSplitPane = new JSplitPane();
        mainSplitPane.setContinuousLayout(false);
        mainSplitPane.setDividerLocation(143);
        mainSplitPane.setDividerSize(5);
        containerPanel.add(mainSplitPane, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainSplitPane.setLeftComponent(panel1);
        indexTabbedPane = new JTabbedPane();
        indexTabbedPane.setFocusable(false);
        indexTabbedPane.setRequestFocusEnabled(false);
        indexTabbedPane.setTabPlacement(2);
        panel1.add(indexTabbedPane, BorderLayout.CENTER);
        cardsPanel = new JPanel();
        cardsPanel.setLayout(new CardLayout(0, 0));
        mainSplitPane.setRightComponent(cardsPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return containerPanel;
    }

}
