package com.dictiographer.desktop.view;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class MainPanel {
    private JPanel contentPane;
    public JTabbedPane indexTabbedPane;
    public JSplitPane mainSplitPane;
    private JPanel contentsPanel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        mainSplitPane = new JSplitPane();
        mainSplitPane.setContinuousLayout(false);
        mainSplitPane.setDividerLocation(143);
        mainSplitPane.setDividerSize(5);
        contentPane.add(mainSplitPane, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        mainSplitPane.setLeftComponent(panel1);
        indexTabbedPane = new JTabbedPane();
        indexTabbedPane.setFocusable(false);
        indexTabbedPane.setRequestFocusEnabled(false);
        indexTabbedPane.setTabPlacement(2);
        panel1.add(indexTabbedPane, BorderLayout.CENTER);
        contentsPanel = new JPanel();
        contentsPanel.setLayout(new CardLayout(0, 0));
        mainSplitPane.setRightComponent(contentsPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
