package com.dictiographer.view;

import com.dictiographer.controller.ViewController;
import com.dictiographer.model.Constants;
import com.dictiographer.model.IndexModel;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class Dictiographer extends JFrame {


    private JPanel contentPane;
    private JTextField textField1;
    private JComboBox domainComboBox;
    private JList list1;
    private JSplitPane mainSplitPane;
    private JEditorPane entryPane;
    private JScrollPane entryScrollPane;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;


    public Dictiographer() {
        $$$setupUI$$$();
        setContentPane(contentPane);

        int w = (int) Double.parseDouble(Constants.PROPS.getProperty(Constants.WIDTH_PROP_KEY));
        int h = (int) Double.parseDouble(Constants.PROPS.getProperty(Constants.HEIGHT_PROP_KEY));
        int x = (int) Double.parseDouble(Constants.PROPS.getProperty(Constants.X_POS_PROP_KEY));
        int y = (int) Double.parseDouble(Constants.PROPS.getProperty(Constants.Y_POS_PROP_KEY));
        int div = Integer.parseInt(Constants.PROPS.getProperty(Constants.DIVIDER_PROP_KEY));

        setSize(w, h);
        setLocation(x, y);
        mainSplitPane.setDividerLocation(div);

        String[] dns = IndexModel.getInstance().getDomains();
        domainComboBox.setModel(new DefaultComboBoxModel(dns));
        if (dns.length > 0) {
            domainComboBox.setEnabled(true);
        }

        String selDomain = Constants.PROPS.getProperty(Constants.SELECTED_DOMAIN_PROP_KEY);
        if (!selDomain.equals("")) {
            domainComboBox.setSelectedItem(selDomain);
        }

        onDomainChanged();


        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                ViewController.getInstance().onClosing(Dictiographer.this);
            }
        });

        domainComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onDomainChanged();
            }
        });

        list1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    setEntry();
                    textField1.requestFocus();
                }

            }
        });


        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                textField1.requestFocus();
            }
        });

    }

    private void setEntry() {
        if (list1.getSelectedValue() != null) {
            Constants.PROPS.setProperty(Constants.SELECTED_WORD_PROP_KEY, list1.getSelectedValue().toString());
            entryPane.setText(ViewController.getInstance().getEntry(domainComboBox.getSelectedItem().toString(), list1.getSelectedValue().toString()));


            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    JViewport jv = entryScrollPane.getViewport();
                    jv.setViewPosition(new Point(0, 0));
                }
            });
//            entryPane.setText("<html><body>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/>test<br/></body></html>");
        }
    }

    private void onDomainChanged() {
        if (domainComboBox.getSelectedItem() == null) {
            return;
        }
        list1.setListData(ViewController.getInstance().getIndex(domainComboBox.getSelectedItem().toString()));
        String selWord = Constants.PROPS.getProperty(Constants.SELECTED_WORD_PROP_KEY);
        if (!selWord.equals("")) {
            list1.setSelectedValue(selWord, true);
            setEntry();
        }
        textField1.requestFocus();
    }

    public int getDividerLocation() {
        return mainSplitPane.getDividerLocation();
    }


    public String getSelectedDomain() {
        Object selItem = domainComboBox.getSelectedItem();
        return selItem == null ? "" : selItem.toString();
    }

    public String getSelectedWord() {
        Object selItem = list1.getSelectedValue();
        return selItem == null ? "" : selItem.toString();
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.CENTER);
        mainSplitPane = new JSplitPane();
        mainSplitPane.setDividerLocation(100);
        panel1.add(mainSplitPane, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        mainSplitPane.setRightComponent(panel2);
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        panel2.add(toolBar1, BorderLayout.NORTH);
        final JToggleButton toggleButton1 = new JToggleButton();
        toggleButton1.setIcon(new ImageIcon(getClass().getResource("/translation.png")));
        toolBar1.add(toggleButton1);
        final JToggleButton toggleButton2 = new JToggleButton();
        toggleButton2.setIcon(new ImageIcon(getClass().getResource("/example.png")));
        toolBar1.add(toggleButton2);
        final JToggleButton toggleButton3 = new JToggleButton();
        toggleButton3.setIcon(new ImageIcon(getClass().getResource("/link.png")));
        toolBar1.add(toggleButton3);
        final JToggleButton toggleButton4 = new JToggleButton();
        toggleButton4.setIcon(new ImageIcon(getClass().getResource("/idiom.png")));
        toolBar1.add(toggleButton4);
        final JToggleButton toggleButton5 = new JToggleButton();
        toggleButton5.setIcon(new ImageIcon(getClass().getResource("/image.png")));
        toolBar1.add(toggleButton5);
        final JToggleButton toggleButton6 = new JToggleButton();
        toggleButton6.setIcon(new ImageIcon(getClass().getResource("/grammar.png")));
        toolBar1.add(toggleButton6);
        entryScrollPane = new JScrollPane();
        panel2.add(entryScrollPane, BorderLayout.CENTER);
        entryPane = new JEditorPane();
        entryPane.setContentType("text/html");
        entryPane.setEditable(false);
        entryPane.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \r\n    </p>\r\n  </body>\r\n</html>\r\n");
        entryScrollPane.setViewportView(entryPane);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        mainSplitPane.setLeftComponent(panel3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(5, 0));
        panel3.add(panel4, BorderLayout.NORTH);
        panel4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(9, 3, 9, 3), null));
        textField1 = new JTextField();
        panel4.add(textField1, BorderLayout.CENTER);
        domainComboBox = new JComboBox();
        domainComboBox.setEnabled(false);
        panel4.add(domainComboBox, BorderLayout.WEST);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1, BorderLayout.CENTER);
        list1 = new JList();
        scrollPane1.setViewportView(list1);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel1.add(panel5, BorderLayout.SOUTH);
        final JToolBar toolBar2 = new JToolBar();
        toolBar2.setBorderPainted(false);
        toolBar2.setFloatable(false);
        panel5.add(toolBar2, BorderLayout.SOUTH);
        button1 = new JButton();
        button1.setIcon(new ImageIcon(getClass().getResource("/application_form_add.png")));
        button1.setText("");
        toolBar2.add(button1);
        button2 = new JButton();
        button2.setIcon(new ImageIcon(getClass().getResource("/application_form_edit.png")));
        button2.setText("");
        toolBar2.add(button2);
        button3 = new JButton();
        button3.setIcon(new ImageIcon(getClass().getResource("/application_form_delete.png")));
        button3.setText("");
        toolBar2.add(button3);
        button4 = new JButton();
        button4.setIcon(new ImageIcon(getClass().getResource("/arrow_refresh.png")));
        button4.setText("");
        toolBar2.add(button4);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
